### DISCUSSION TITLE
[Allowed_dms_user_ids]

### DISCUSSION THREAD

**Discussion by Quelling** [jakobdylanc/llmcord.py#88] [Ideas]
Can you add a feature to allow DMs only for specific user IDs?

**Comment by jakobdylanc** [comment]
I can see why this would be useful.

Just so you know, only users that are in a mutual server with the bot can DM it. So it's not like everybody in the world can use it.

**Reply by Quelling** [reply]
> I can see why this would be useful.
> 
> Just so you know, only users that are in a mutual server with the bot can DM it. So it's not like everybody in the world can use it.

I just added it to my server, where there are a lot of people, and some people deliberately come and overload the API.

**Reply by jakobdylanc** [reply]
Sorry about that. I'll look into this. I'm thinking I want to overhaul the permissions settings entirely to make them more flexible and less confusing.

**Reply by jakobdylanc** [reply]
Here's what I'm thinking...

Replace these config settings:
```yaml
allowed_channel_ids: []
allowed_role_ids: []
blocked_user_ids: []
```

With this:
```yaml
permissions:
  channels:
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  users:
    allowed_ids: []
    blocked_ids: []
```

Behavior:
- `channels` and `roles` categories do not affect DMs
  - Use `users` category to limit who can DM, or `allow_dms` to disable entirely
- When `allowed_ids` is empty it allows ALL in that category
- Entries in `blocked_ids` are ALWAYS blocked, even if also present in `allowed_ids`
- If `allowed_ids` is NOT empty in both `roles` and `users` categories, user only needs 1 to be considered allowed (allowed user ID OR has an allowed role)

Thoughts? Feedback? Am I missing anything?
